### ISSUE TITLE
Option to generate a binary file from the hex output?

### ISSUE THREAD

**Issue by dplassgit** [ept221/8085-Assembler#2]
I'd like to generate a pure binary file from the hex - is there an option for this?

**Comment by ept221** [comment]
Not currently, but that would be very easy to add. You would just need to modify the function named `output` in `assembler.py`. How exactly would you like the output formatted? For example, you would probably want a way to set the start and end address for the binary. Are there any other features or options you would like? I might be able to add them today.

**Comment by dplassgit** [comment]
Looks like a fork https://github.com/sobkas/8085-Assembler-tsr80-100 does exactly what I need. (I'm in fact trying  to generate 8085 for TRS-80 model 100)

**Comment by ept221** [comment]
@dplassgit If it's helpful, I've just added binary support similar to that repo, and now allow for the use of different number formats in the input assembly (decimal, hex, binary) and negative numberers stored in two's compliment format. Strings have also been added. Also empty segments that result in moving the origin are now shown in the output by default (except with the `-s` option, for readability), but you can turn this off with `-c`.
