### ISSUE TITLE
RST lookup error 'Instruction has bad register/register-pair'

### ISSUE THREAD

**Issue by Kayto** [ept221/8085-Assembler#5]
Thanks for sharing this. Minor issue as follows.

RST lookup fails with error 'Instruction has bad register/register-pair'.
i.e . RST 1 fails the numeric lookup.

I crudely worked around by adding an underscore to the 'RST #' references in instructions.py and listing all RST_# values in the mnm_0 table.py.

I am sure there is a neater way but works.

**Comment by ept221** [comment]
Hi, yeah I don't have RST codes built in. I'll be sure to add those soon, hopefully later this week. If you want any other features added, please feel free to post them!

**Comment by ept221** [comment]
Okay, RST 1, and others should now work just fine, without a need for the underscore patch. Let me know if you need anything else!
